<?php
use Album\Model\Album;
?>
</div> <!-- escape layout container -->

<div class="well" >
    <div class="container">
        <div>
            <h1 style="font-size: 63px;">Spotify Example</h1>
            <p class="lead">Search Spotify and view albums with this application.</p>
        </div>

        <form method="post" name="album" id="album" class="form-horizontal">
            <div class="row">
                <div class="col-xs-10">
                    <div class="input-group-lg">
                        <?php

                        echo $this->formElement($this->form->get('album')); ?>
                    </div>
                </div>
                <div class="col-xs-2 input-group-lg">
                    <input type="submit" name="submit" id="submitbutton" value="Search" class="btn btn-success btn-lg btn-block">
                </div>
            </div>
        </form>
    </div>
</div>

<div class="container" style="margin-top: 60px">
    <div class="row">


    <?php if(!empty($this->albums)) {
        /** @var Album $album */
        foreach ($this->albums as $album) {
            ?>
            <div class="col-xs-4 album">
                <div class="album-cover-image center-block">
                    <a href="<?=$this->url('album', ['action'=>'view', 'id' => $album->getAlbumId()])?>">
                        <img src="<?= $album->getPhotoPreview() ?: 'http://communityvoices.post-gazette.com/spot.png'?>" class="album-image">
                    </a>
                </div>
                <a href="<?=$this->url('album', ['action'=>'view', 'id' => $album->getAlbumId()])?>"><?=$album->getName()?></a>
            </div>
            <?php
        }
    }?>
    </div>
</div>



<!-- resume layout container -->
<div class="container">