<?php
use Album\Model\Album;

/** @var Album $album */
$album = $this->album;
?>
<div class="row">
    <div class="col-xs-12">
        <h4><?=$album->getName()?></h4>
    </div>
</div>
<div class="row">
    <div class="col-xs-6">
        <img src="<?= $album->getPhotoPreview() ?: 'http://communityvoices.post-gazette.com/spot.png'?>" width="100%">
    </div>
    <div class="col-xs-6">
        <p>Album Tracks</p>
        <ol>
            <?php foreach($album->getTracks() as $track) {?>
            <li class="marginTop10"><a href="<?=$track->getPreviewUrl()?>" target="_blank"><?=$track->getName()?></a></li>
            <?php } ?>
        </ol>
    </div>
</div>